<<<<<<< HEAD
# Generated by Django 2.1 on 2019-09-18 10:59
=======
# Generated by Django 2.1 on 2019-09-18 10:58
>>>>>>> origin/master

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='验证码', max_length=20, verbose_name='验证码')),
                ('mobile', models.CharField(help_text='电话', max_length=11, verbose_name='电话')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '短信验证码',
                'verbose_name_plural': '短信验证码',
=======
            name='Testinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=100, verbose_name='测试数据')),
            ],
            options={
                'verbose_name': '测试信息',
                'verbose_name_plural': '测试信息',
>>>>>>> origin/master
            },
        ),
    ]
