# Generated by Django 2.1 on 2019-09-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=100, verbose_name='测试数据')),
            ],
            options={
                'verbose_name': '测试信息',
                'verbose_name_plural': '测试信息',
            },
        ),
    ]
