# Generated by Django 2.1 on 2019-09-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_testinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testinfo',
        ),
    ]
