# Generated by Django 2.1 on 2019-09-19 14:57

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import goods.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('goods_num', models.CharField(max_length=50, verbose_name='商品编号')),
                ('main_img', models.ImageField(blank=True, null=True, upload_to=goods.models.goods_main, verbose_name='商品主图')),
                ('limit_num', models.IntegerField(default=0, verbose_name='限购数量')),
                ('out_stock', models.IntegerField(verbose_name='上架数量')),
                ('upper', models.DateTimeField(default=datetime.datetime.now, verbose_name='上架时间')),
                ('lower', models.CharField(blank=True, default='', max_length=20, verbose_name='下架时间')),
                ('all_stock', models.IntegerField(verbose_name='仓库库存')),
                ('ratio', models.IntegerField(verbose_name='打几折')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='市场价')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='成本价')),
                ('start_time', models.CharField(blank=True, default='', max_length=20, verbose_name='开卖时间')),
                ('allimg', DjangoUeditor.models.UEditorField(default='', verbose_name='商品详情')),
                ('express', models.CharField(choices=[('baoyou', '卖家包邮'), ('daofu', '买家到付')], max_length=10, verbose_name='快递方式')),
            ],
            options={
                'verbose_name_plural': '基础信息',
                'verbose_name': '基础信息',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=50, verbose_name='订单编号')),
                ('buy_phone', models.CharField(max_length=20, verbose_name='买家')),
                ('goods_num', models.CharField(max_length=50, verbose_name='商品编号')),
                ('buy_num', models.IntegerField(verbose_name='购买数量')),
                ('pay_money', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='订单总价格')),
                ('buy_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='购买时间')),
                ('state', models.CharField(choices=[('not_pay', '未付款'), ('ok_pay', '已付款'), ('send_goods', '已发货'), ('get_goods', '确认收货'), ('success', '交易成功'), ('cancel', '已撤销')], default='cancel', max_length=20, verbose_name='进度状态')),
                ('finish_time', models.CharField(blank=True, max_length=20, verbose_name='完成时间')),
                ('buy_addr', models.CharField(blank=True, max_length=50, verbose_name='收货地址')),
            ],
            options={
                'verbose_name_plural': '订单信息',
                'verbose_name': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='分类编号')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('f_num', models.IntegerField(default=0, verbose_name='父类编号')),
                ('ico', models.ImageField(blank=True, upload_to=goods.models.goods_type, verbose_name='子类图标')),
            ],
            options={
                'verbose_name_plural': '商品分类',
                'verbose_name': '商品分类',
            },
        ),
        migrations.AddField(
            model_name='goodsbase',
            name='type_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_num', to='goods.Type', verbose_name='分类编码'),
        ),
    ]
